"""Need Group validation for detailed CRM Action-to-Need links."""

from __future__ import annotations

from typing import Final

INTERNAL_ACTION_CATEGORY = "INTERNAL"

# The value is the detailed CRM Need.code, not the Need Group. A Need code
# may be reused by many Actions; INTERNAL Actions intentionally have no Need.
ACTION_NEED_CODE_BY_ACTION: Final[dict[str, str | None]] = {
	"CALL": "FIRST_CONTACT",
	"SEND_ZALO": "FOLLOW_UP",
	"SEND_EMAIL": "FOLLOW_UP",
	"SEND_SMS": "FOLLOW_UP",
	"VIDEO_CALL": "FOLLOW_UP",
	"CALL_BACK": "CALLBACK",
	"REASSIGN_ADVISOR": "FOLLOW_UP",
	"ESCALATE_SUPERVISOR": "FOLLOW_UP",
	"SEND_MAJOR_INFO": "PROGRAM_INFORMATION",
	"SEND_PROGRAM_INFO": "PROGRAM_INFORMATION",
	"SEND_TUITION_INFO": "TUITION_INFORMATION",
	"SEND_SCHOLARSHIP_INFO": "SCHOLARSHIP_INFORMATION",
	"SEND_PROMOTION_INFO": "TUITION_INFORMATION",
	"SEND_ADMISSION_INFO": "ADMISSION_INFORMATION",
	"SEND_DORM_INFO": "PROGRAM_INFORMATION",
	"SEND_CAREER_INFO": "CAREER_INFORMATION",
	"SEND_BROCHURE": "PROGRAM_INFORMATION",
	"SEND_MAJOR_VIDEO": "PROGRAM_INFORMATION",
	"SEND_RELEVANT_FAQ": "PROGRAM_INFORMATION",
	"INVITE_OPEN_DAY": "EVENT_ENGAGEMENT",
	"INVITE_CAMPUS_TOUR": "CAMPUS_EXPERIENCE",
	"INVITE_WEBINAR": "EVENT_ENGAGEMENT",
	"INVITE_WORKSHOP": "EVENT_ENGAGEMENT",
	"INVITE_CLASS_EXPERIENCE": "CAMPUS_EXPERIENCE",
	"INVITE_STEM_EVENT": "EVENT_ENGAGEMENT",
	"INVITE_MOCK_TEST": "EVENT_ENGAGEMENT",
	"BOOK_1ON1_CONSULTATION": "COUNSELING",
	"SEND_PERSONALIZED_CONTENT": "COUNSELING",
	"SEND_TESTIMONIAL": "EVENT_ENGAGEMENT",
	"REMIND_APPLICATION": "APPLICATION_GUIDANCE",
	"REMIND_COMPLETE_APPLICATION": "APPLICATION_INCOMPLETE",
	"REQUEST_MISSING_DOCUMENT": "DOCUMENT_SUPPORT",
	"GUIDE_NEXT_STEP": "APPLICATION_GUIDANCE",
	"CHECK_APPLICATION": "APPLICATION_INCOMPLETE",
	"SEND_APPLICATION_CHECKLIST": "APPLICATION_GUIDANCE",
	"REMIND_APPLICATION_DEADLINE": "APPLICATION_DEADLINE",
	"ASSIST_APPLICATION_FEE": "APPLICATION_GUIDANCE",
	"CONFIRM_APPLICATION_RECEIVED": "APPLICATION_GUIDANCE",
	"ADVISE_MAJOR": "DECISION_SUPPORT",
	"ADVISE_TUITION": "FINANCIAL_SUPPORT",
	"ADVISE_SCHOLARSHIP": "FINANCIAL_SUPPORT",
	"ADVISE_CAREER": "DECISION_SUPPORT",
	"ADVISE_PARENT": "DECISION_SUPPORT",
	"COMPARE_MAJORS": "DECISION_SUPPORT",
	"COMPARE_CAMPUSES": "DECISION_SUPPORT",
	"SEND_OFFER": "ENROLLMENT_SUPPORT",
	"REMIND_ENROLLMENT_DEADLINE": "ENROLLMENT_SUPPORT",
	"INVITE_CAMPUS_VISIT": "DECISION_SUPPORT",
	"ESCALATE_HIGH_INTENT": "ENROLLMENT_SUPPORT",
	"CONTACT_PARENT": "PARENT_ENGAGEMENT",
	"SEND_PARENT_TUITION": "PARENT_COUNSELING",
	"SEND_PARENT_SCHOLARSHIP": "PARENT_COUNSELING",
	"SEND_TRAINING_ROADMAP": "PARENT_COUNSELING",
	"SEND_PARENT_CAREER_INFO": "PARENT_COUNSELING",
	"INVITE_PARENT_EVENT": "PARENT_ENGAGEMENT",
	"BOOK_PARENT_CONSULTATION": "PARENT_COUNSELING",
	"SEND_FINANCIAL_PLAN": "PARENT_COUNSELING",
	"FOLLOW_UP_SILENT_LEAD": "NO_RESPONSE",
	"REENGAGE_LEAD": "RE_ENGAGEMENT",
	"ASK_DECISION_REASON": "NOT_READY",
	"SEND_OBJECTION_CONTENT": "NOT_READY",
	"ESCALATE_TO_SENIOR": "NOT_READY",
	"SCHEDULE_LATER_FOLLOWUP": "NOT_READY",
	"ADD_TO_NURTURE": "NOT_READY",
	"MARK_NOT_READY": "NOT_READY",
	"MARK_LOST": "RE_ENGAGEMENT",
	"ACTIVATE_WINBACK": "RE_ENGAGEMENT",
	"CREATE_TASK": None,
	"ASSIGN_LEAD": None,
	"REASSIGN_LEAD": None,
	"CREATE_REMINDER": None,
	"CREATE_APPOINTMENT": None,
	"CREATE_CAMPAIGN": None,
	"UPDATE_LEAD_STATUS": None,
	"UPDATE_LEAD_SCORE": None,
	"ADD_TAG": None,
	"CREATE_NOTE": None,
	"ESCALATE_CASE": None,
	"REQUEST_SUPERVISOR_REVIEW": None,
}


def need_code_for_action(action_code: str | None) -> str | None:
	"""Return the configured detailed Need.code for a canonical Action."""
	return ACTION_NEED_CODE_BY_ACTION.get(str(action_code or "").strip().upper())


def need_group_for_action_category(action_category: str | None) -> str | None:
	"""Return the Need Group code used to validate a detailed Need link.

	The controlled Need catalogue prefixes business groups with ``NEED_`` while
	CRM Action categories use the unprefixed code. Internal bookkeeping Actions
	do not represent a student Need and therefore have no mapping.
	"""
	category = str(action_category or "").strip().upper()
	if not category or category == INTERNAL_ACTION_CATEGORY:
		return None
	return f"NEED_{category}"


def need_group_matches_action(action_category: str | None, need_group: str | None) -> bool:
	"""Return whether a Need Group is valid for an Action category."""
	expected_group = need_group_for_action_category(action_category)
	return need_group == expected_group if expected_group else not need_group
