<template>
  <LayoutHeader><template #left-header><ViewBreadcrumbs routeName="Lead Sales Tasks" /></template><template #right-header><Button :label="__('Làm mới')" iconLeft="refresh-cw" :loading="resource.loading" @click="reset" /></template></LayoutHeader>
  <main class="h-full overflow-y-auto bg-surface-gray-2/40 p-4 sm:p-5"><div class="mx-auto max-w-7xl"><LeadSalesPageState :loading="resource.loading" :error="resource.error" :has-data="Boolean(data)" @retry="reset"><section class="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-xl font-semibold">{{ __('Việc nhóm') }}</h1><LeadSalesDefinition class="mt-1" :definition="workspaceDefinition(data)" :timestamp="formatWorkspaceTimestamp(data)" /></div><FormControl v-model="status" type="select" :options="statuses" :label="__('Trạng thái')" class="w-44" @update:modelValue="reset" /></section><div v-if="displayedRows.length" class="overflow-x-auto rounded-lg border border-outline-gray-2 bg-surface-white"><table class="w-full min-w-[850px] text-sm"><thead class="bg-surface-gray-2 text-left text-ink-gray-6"><tr><th class="px-4 py-3">{{ __('Công việc') }}</th><th class="px-4 py-3">{{ __('Hồ sơ') }}</th><th class="px-4 py-3">{{ __('Người phụ trách') }}</th><th class="px-4 py-3">{{ __('Trạng thái') }}</th><th class="px-4 py-3">{{ __('Hạn xử lý') }}</th></tr></thead><tbody><tr v-for="row in displayedRows" :key="row.name" class="border-t border-outline-gray-1"><td class="px-4 py-3"><p class="font-medium">{{ row.action_type || __('Công việc') }}</p><p v-if="row.objective" class="mt-0.5 text-xs text-ink-gray-5">{{ row.objective }}</p></td><td class="px-4 py-3"><RouterLink v-if="row.student" class="text-[--brand-ink] hover:underline" :to="{ name: 'CRM Student', params: { crmStudentId: row.student } }">{{ row.student_name || row.student }}</RouterLink><span v-else>—</span></td><td class="px-4 py-3">{{ row.action_owner || '—' }}</td><td class="px-4 py-3"><Badge :label="row.execution_status || row.state || '—'" variant="subtle" theme="gray" /></td><td class="px-4 py-3">{{ row.due_at ? formatDate(row.due_at) : '—' }}</td></tr></tbody></table></div><p v-else class="rounded-lg border border-outline-gray-2 bg-surface-white p-6 text-sm text-ink-gray-5">{{ __('Không có việc nhóm phù hợp.') }}</p><div v-if="data?.next_cursor" class="mt-4 flex justify-center"><Button :label="__('Tải thêm')" :loading="resource.loading" @click="loadMore" /></div></LeadSalesPageState></div></main>
</template>
<script setup>
import LayoutHeader from '@/components/LayoutHeader.vue'; import ViewBreadcrumbs from '@/components/ViewBreadcrumbs.vue'; import LeadSalesDefinition from '@/components/LeadSales/LeadSalesDefinition.vue'; import LeadSalesPageState from '@/components/LeadSales/LeadSalesPageState.vue'; import { createLeadSalesWorkspaceResource, formatWorkspaceTimestamp, workspaceDefinition, workspaceRows } from '@/data/leadSalesWorkspace'; import { formatDate } from '@/utils'; import { Badge, Button, FormControl } from 'frappe-ui'; import { computed, ref, watch } from 'vue'
const status = ref('open'); const resource = createLeadSalesWorkspaceResource('actions', { status: status.value }); const data = computed(() => resource.data); const displayedRows = ref([]); const appending = ref(false); const statuses = [{ label: __('Đang mở'), value: 'open' }, { label: __('Hoàn thành'), value: 'completed' }, { label: __('Ngoại lệ'), value: 'exception' }, { label: __('Tất cả'), value: 'all' }]
watch(data, (payload) => { const nextRows = workspaceRows(payload, 'rows'); displayedRows.value = appending.value ? [...new Map([...displayedRows.value, ...nextRows].map((row) => [row.name, row])).values()] : nextRows; appending.value = false }, { immediate: true })
function reset() { appending.value = false; displayedRows.value = []; resource.submit({ status: status.value }) } function loadMore() { appending.value = true; resource.submit({ status: status.value, cursor: data.value?.next_cursor }) }
</script>
