<template>
  <LayoutHeader><template #left-header><ViewBreadcrumbs routeName="Lead Sales Performance" /></template><template #right-header><Button :label="__('Làm mới')" iconLeft="refresh-cw" :loading="resource.loading" @click="resource.reload()" /></template></LayoutHeader>
  <main class="h-full overflow-y-auto bg-surface-gray-2/40 p-4 sm:p-5"><div class="mx-auto max-w-7xl"><LeadSalesPageState :loading="resource.loading" :error="resource.error" :has-data="Boolean(data)" @retry="resource.reload()"><section class="mb-4 flex flex-wrap items-end justify-between gap-3"><div><h1 class="text-xl font-semibold">{{ __('Hiệu suất thành viên') }}</h1><LeadSalesDefinition class="mt-1" :definition="workspaceDefinition(data)" :timestamp="formatWorkspaceTimestamp(data)" /></div><FormControl v-model="period" type="select" :options="periods" :label="__('Kỳ báo cáo')" class="w-44" @update:modelValue="reload" /></section><div v-if="members.length" class="overflow-x-auto rounded-lg border border-outline-gray-2 bg-surface-white"><table class="w-full min-w-[700px] text-sm"><thead class="bg-surface-gray-2 text-left text-ink-gray-6"><tr><th class="px-4 py-3">{{ __('Thành viên') }}</th><th class="px-4 py-3 text-right">{{ __('Hồ sơ') }}</th><th class="px-4 py-3 text-right">{{ __('Việc hiện tại') }}</th><th class="px-4 py-3 text-right">{{ __('Đã hoàn thành') }}</th><th class="px-4 py-3 text-right">{{ __('SLA trễ') }}</th></tr></thead><tbody><tr v-for="member in members" :key="member.staff" class="border-t border-outline-gray-1"><td class="px-4 py-3 font-medium">{{ member.name || member.staff }}</td><td class="px-4 py-3 text-right">{{ member.students ?? 0 }}</td><td class="px-4 py-3 text-right">{{ member.current_actions ?? 0 }}</td><td class="px-4 py-3 text-right">{{ member.completed_actions ?? 0 }}</td><td class="px-4 py-3 text-right">{{ member.breached_sla ?? 0 }}</td></tr></tbody></table></div><p v-else class="rounded-lg border border-outline-gray-2 bg-surface-white p-6 text-sm text-ink-gray-5">{{ __('Chưa có thành viên hoặc hoạt động trong kỳ đã chọn.') }}</p></LeadSalesPageState></div></main>
</template>
<script setup>
import LayoutHeader from '@/components/LayoutHeader.vue'; import ViewBreadcrumbs from '@/components/ViewBreadcrumbs.vue'; import LeadSalesDefinition from '@/components/LeadSales/LeadSalesDefinition.vue'; import LeadSalesPageState from '@/components/LeadSales/LeadSalesPageState.vue'; import { createLeadSalesWorkspaceResource, formatWorkspaceTimestamp, workspaceDefinition, workspaceRows } from '@/data/leadSalesWorkspace'; import { Button, FormControl } from 'frappe-ui'; import { computed, ref } from 'vue'
const period = ref('30d'); const resource = createLeadSalesWorkspaceResource('performance', { period: period.value }); const data = computed(() => resource.data); const members = computed(() => workspaceRows(data.value, 'members')); const periods = [{ label: __('7 ngày'), value: '7d' }, { label: __('30 ngày'), value: '30d' }, { label: __('Tháng này'), value: 'this_month' }]
function reload() { resource.submit({ period: period.value }) }
</script>
