"""CRUD API for CRM Campaign records."""

from __future__ import annotations

import re
from datetime import date
from typing import Any

import frappe
from frappe import _
from frappe.rate_limiter import rate_limit

from crm.api._pagination import paged_list

CAMPAIGN_FIELDS = [
	"name",
	"stable_code",
	"title",
	"campus",
	"campaign_type",
	"event_type",
	"status",
	"start_date",
	"end_date",
	"budget",
	"owner_staff",
	"owning_team",
	"platform",
	"channel_boundary",
	"channel_type",
	"channel_url",
	"utm_source",
	"utm_medium",
	"utm_campaign",
	"kpi_target_leads",
	"kpi_target_enrollments",
	"notes",
	"owner",
	"creation",
	"modified",
]

# ``name`` is derived from ``title`` and ``stable_code`` is generated by the
# DocType controller. Audit fields are also intentionally excluded.
WRITABLE_FIELDS = [
	"title",
	"campus",
	"campaign_type",
	"event_type",
	"status",
	"start_date",
	"end_date",
	"budget",
	"owner_staff",
	"owning_team",
	"platform",
	"channel_boundary",
	"channel_type",
	"channel_url",
	"utm_source",
	"utm_medium",
	"utm_campaign",
	"kpi_target_leads",
	"kpi_target_enrollments",
	"notes",
]

PUBLIC_CAMPAIGN_FIELDS = (
	"name",
	"stable_code",
	"title",
	"campus",
	"campaign_type",
	"event_type",
	"status",
	"start_date",
	"end_date",
	"platform",
	"channel_boundary",
	"channel_type",
	"channel_url",
	"utm_source",
	"utm_medium",
	"utm_campaign",
)
MAX_PUBLIC_CAMPAIGN_PAGE_LENGTH = 100
_PUBLIC_DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _set_writable_fields(doc: Any, values: dict[str, Any]) -> None:
	for fieldname in WRITABLE_FIELDS:
		if fieldname in values:
			doc.set(fieldname, values[fieldname])


def _set_date_filter(filters: dict[str, Any], fieldname: str, date_from: Any, date_to: Any) -> None:
	if date_from and date_to:
		filters[fieldname] = ["between", [date_from, date_to]]
	elif date_from:
		filters[fieldname] = [">=", date_from]
	elif date_to:
		filters[fieldname] = ["<=", date_to]


def _parse_public_date(value: Any, fieldname: str) -> date | None:
	value = str(value or "").strip()
	if not value:
		return None
	if not _PUBLIC_DATE_PATTERN.fullmatch(value):
		frappe.throw(_("{0} must use YYYY-MM-DD format.").format(fieldname), frappe.ValidationError)
	try:
		return date.fromisoformat(value)
	except ValueError:
		frappe.throw(_("{0} must be a valid date.").format(fieldname), frappe.ValidationError)


def _coalesce_public_date(primary: Any, alias: Any, fieldname: str) -> str | None:
	primary = str(primary or "").strip()
	alias = str(alias or "").strip()
	if primary and alias and primary != alias:
		frappe.throw(_("Only one value may be provided for {0}.").format(fieldname), frappe.ValidationError)
	return primary or alias or None


def _parse_public_int(
	value: Any, fieldname: str, *, default: int, minimum: int, maximum: int | None = None
) -> int:
	if value in (None, ""):
		return default
	try:
		parsed = int(value)
	except (TypeError, ValueError):
		frappe.throw(_("{0} must be an integer.").format(fieldname), frappe.ValidationError)
	if parsed < minimum or (maximum is not None and parsed > maximum):
		bounds = f"{minimum} and {maximum}" if maximum is not None else f"at least {minimum}"
		frappe.throw(_("{0} must be between {1}.").format(fieldname, bounds), frappe.ValidationError)
	return parsed


@frappe.whitelist()
def list_campaigns(
	status: str | None = None,
	campus: str | None = None,
	campaign_type: str | None = None,
	event_type: str | None = None,
	owner_staff: str | None = None,
	owning_team: str | None = None,
	platform: str | None = None,
	channel_boundary: str | None = None,
	channel_type: str | None = None,
	stable_code: str | None = None,
	start_date_from: str | None = None,
	start_date_to: str | None = None,
	end_date_from: str | None = None,
	end_date_to: str | None = None,
	search: str | None = None,
	start: int | str = 0,
	page_length: int | str = 20,
	lead_only: bool | str = False,
) -> dict[str, Any]:
	"""List campaigns with allow-listed filters and offset pagination."""
	filters: dict[str, Any] = {}
	for fieldname, value in (
		("status", status),
		("campus", campus),
		("campaign_type", campaign_type),
		("event_type", event_type),
		("owner_staff", owner_staff),
		("owning_team", owning_team),
		("platform", platform),
		("channel_boundary", channel_boundary),
		("channel_type", channel_type),
		("stable_code", stable_code),
	):
		if value not in (None, ""):
			filters[fieldname] = value

	_set_date_filter(filters, "start_date", start_date_from, start_date_to)
	_set_date_filter(filters, "end_date", end_date_from, end_date_to)
	if str(lead_only).strip().lower() in {"1", "true", "yes"} or lead_only is True:
		lead_campaigns = frappe.get_list(
			"CRM Lead",
			filters={"campaign": ["is", "set"]},
			fields=["campaign"],
			limit_page_length=0,
		)
		campaign_names = sorted({row.get("campaign") for row in lead_campaigns if row.get("campaign")})
		filters["name"] = ["in", campaign_names or ["__no_visible_campaign__"]]

	or_filters = None
	if search:
		like = f"%{search}%"
		or_filters = [
			["title", "like", like],
			["stable_code", "like", like],
			["utm_source", "like", like],
			["utm_medium", "like", like],
			["utm_campaign", "like", like],
		]

	result = paged_list(
		"CRM Campaign",
		CAMPAIGN_FIELDS,
		filters=filters,
		or_filters=or_filters,
		start=start,
		page_length=page_length,
		order_by="start_date desc, modified desc, name desc",
	)
	rows = result.pop("rows")
	return {**result, "campaigns": rows}


@frappe.whitelist(allow_guest=True, methods=["GET"])
@rate_limit(limit=120, seconds=60)
def get_public_campaigns(
	campaign_code: str | None = None,
	startdate: str | None = None,
	enddate: str | None = None,
	start_date: str | None = None,
	end_date: str | None = None,
	start: int | str = 0,
	page_length: int | str = 20,
) -> dict[str, Any]:
	"""Return public campaign metadata with optional date filtering."""
	start_value = _parse_public_date(
		_coalesce_public_date(startdate, start_date, "startdate/start_date"), "startdate"
	)
	end_value = _parse_public_date(_coalesce_public_date(enddate, end_date, "enddate/end_date"), "enddate")
	if start_value and end_value and start_value > end_value:
		frappe.throw(_("startdate cannot be greater than enddate."), frappe.ValidationError)

	start = _parse_public_int(start, "start", default=0, minimum=0)
	page_length = _parse_public_int(
		page_length,
		"page_length",
		default=20,
		minimum=1,
		maximum=MAX_PUBLIC_CAMPAIGN_PAGE_LENGTH,
	)

	filters: list[list[Any]] = []
	if campaign_code not in (None, ""):
		filters.append(["stable_code", "=", str(campaign_code).strip()])
	if start_value:
		filters.append(["start_date", ">=", str(start_value)])
	if end_value:
		filters.append(["end_date", "<=", str(end_value)])

	rows = frappe.get_all(
		"CRM Campaign",
		filters=filters,
		fields=list(PUBLIC_CAMPAIGN_FIELDS),
		order_by="start_date asc, stable_code asc, name asc",
		limit_start=start,
		limit_page_length=page_length,
	)
	return {
		"total": frappe.db.count("CRM Campaign", filters=filters),
		"start": start,
		"page_length": page_length,
		"campaigns": [dict(row) for row in rows],
	}


@frappe.whitelist()
def get_campaign(code: str | None = None, name: str | None = None) -> dict[str, Any]:
	"""Get one campaign by stable code, with legacy name support."""
	identifier = (code or name or "").strip()
	if not identifier:
		frappe.throw(_("Campaign code is required."), frappe.ValidationError)

	campaign_name = frappe.db.get_value(
		"CRM Campaign",
		{"stable_code": identifier},
		"name",
	)
	if not campaign_name and frappe.db.exists("CRM Campaign", identifier):
		campaign_name = identifier

	doc = frappe.get_doc("CRM Campaign", campaign_name or identifier)
	doc.check_permission("read")
	return doc.as_dict()


@frappe.whitelist(methods=["POST"])
def create_campaign(**values: Any) -> dict[str, Any]:
	"""Create a campaign; server-managed fields cannot be supplied by callers."""
	doc = frappe.new_doc("CRM Campaign")
	_set_writable_fields(doc, values)
	doc.insert()
	return doc.as_dict()


@frappe.whitelist(methods=["POST", "PUT"])
def update_campaign(name: str, **values: Any) -> dict[str, Any]:
	"""Update a campaign while keeping its server-generated code immutable."""
	doc = frappe.get_doc("CRM Campaign", name)
	doc.check_permission("write")
	if "stable_code" in values and values["stable_code"] != doc.stable_code:
		frappe.throw(_("Campaign Code is immutable after creation."), frappe.ValidationError)
	values.pop("stable_code", None)
	values.pop("name", None)
	_set_writable_fields(doc, values)
	doc.save()
	return doc.as_dict()


@frappe.whitelist(methods=["DELETE", "POST"])
def delete_campaign(name: str) -> dict[str, str]:
	"""Delete a campaign after checking delete permission."""
	doc = frappe.get_doc("CRM Campaign", name)
	doc.check_permission("delete")
	doc.delete()
	return {"deleted": name}
