"""CRUD API for CRM Lead records.

The Lead DocType owns validation, ownership changes and
processing commands. This module only exposes the ordinary CRUD boundary and
keeps those server-managed workflows out of generic field updates.
"""

from __future__ import annotations

import json
import re
from typing import Any

import frappe
from frappe import _

from crm.api._pagination import paged_list

DOCTYPE = "CRM Lead"
MAX_PAGE_LENGTH = 100
LAYOUT_FIELD_TYPES = {"Column Break", "Section Break", "Tab Break", "HTML"}
NON_FILTERABLE_FIELD_TYPES = LAYOUT_FIELD_TYPES | {"Table", "Table MultiSelect"}

LIST_FIELDS = [
	"name",
	"lead_code",
	"processing_status",
	"resolution",
	"student_name",
	"phone",
	"email",
	"other_email",
	"high_school",
	"current_grade",
	"study_stage",
	"province",
	"ward",
	"branch",
	"major",
	"aspiration",
	"source",
	"advertising_channel",
	"campaign",
	"conversion_potential",
	"segments",
	"admission_year",
	"notes",
	"owner_staff",
	"assigned_to",
	"student",
	"creation",
	"modified",
]

# These fields are either generated by the Lead controller, projections of a
# command-owned workflow, audit trails, or identity links created by the
# conversion services. Keeping the list here makes the generic CRUD boundary
# explicit even when a field is not marked read_only in the DocType schema.
SERVER_MANAGED_FIELDS = frozenset(
	{
		"name",
		"doctype",
		"naming_series",
		"owner",
		"creation",
		"modified",
		"modified_by",
		"lead_code",
		"processing_status",
		"resolution",
		"resolution_reason",
		"matched_student",
		"conversion_blockers",
		"converted_student",
		"converted_at",
		"assigned_to",
		"owner_staff",
		"owning_team",
		"owning_pool",
		"latest_score",
		"assessment_status",
		"assessment_revision",
		"interest_level",
		"fit_level",
		"primary_barrier",
		"student_context_revision",
		"privacy_status",
		"status_change_log",
		"assignment_log",
		"student",
		"identity",
		"case_key",
		"ownership_revision",
		"engagement_revision",
		"lifecycle_revision",
		"sla_evidence_state",
		"sla_evidence_observed_at",
		"score_input_revision",
		"applied_score_input_revision",
		"applied_policy_revision",
		"intake_integrity_state",
		"intake_quarantine_reason",
	}
)

SEARCH_FIELDS = (
	"name",
	"lead_code",
	"student_name",
	"phone",
	"email",
	"high_school",
	"owner_staff",
	"source",
	"campaign",
)
ORDER_FIELD_PATTERN = re.compile(r"^(name|lead_code|student_name|creation|modified)\s+(asc|desc)$", re.I)


def _parse_json_object(value: Any, fieldname: str) -> dict[str, Any]:
	if value in (None, ""):
		return {}
	if isinstance(value, str):
		try:
			value = json.loads(value)
		except (TypeError, ValueError):
			frappe.throw(_("{0} must be valid JSON.").format(fieldname), frappe.ValidationError)
	if not isinstance(value, dict):
		frappe.throw(_("{0} must be an object.").format(fieldname), frappe.ValidationError)
	return dict(value)


def _payload_from_arguments(fields: Any, direct_values: dict[str, Any]) -> dict[str, Any]:
	nested_values = _parse_json_object(fields, "fields")
	direct_values = {key: value for key, value in direct_values.items() if key != "cmd"}
	if nested_values and direct_values:
		frappe.throw(_("Send either fields or direct Lead fields, not both."), frappe.ValidationError)
	return nested_values or direct_values


def _parse_int(value: Any, fieldname: str, *, default: int, minimum: int, maximum: int | None = None) -> int:
	if value in (None, ""):
		return default
	try:
		parsed = int(value)
	except (TypeError, ValueError):
		frappe.throw(_("{0} must be an integer.").format(fieldname), frappe.ValidationError)
	if parsed < minimum or (maximum is not None and parsed > maximum):
		bounds = f"{minimum} and {maximum}" if maximum is not None else f"at least {minimum}"
		frappe.throw(_("{0} must be between {1}.").format(fieldname, bounds), frappe.ValidationError)
	return parsed


def _parse_order_by(value: Any) -> str:
	value = str(value or "modified desc").strip()
	match = ORDER_FIELD_PATTERN.fullmatch(value)
	if not match:
		frappe.throw(
			_("order_by must use an allow-listed field and direction (for example, 'modified desc')."),
			frappe.ValidationError,
		)
	fieldname, direction = match.groups()
	direction = direction.lower()
	return f"{fieldname.lower()} {direction}, name {direction}"


def _meta_fieldnames() -> set[str]:
	return {field.fieldname for field in frappe.get_meta(DOCTYPE).fields if field.fieldname}


def _writable_fieldnames() -> set[str]:
	writable = set()
	for field in frappe.get_meta(DOCTYPE).fields:
		if (
			field.fieldname
			and field.fieldtype not in LAYOUT_FIELD_TYPES
			and not field.read_only
			and field.fieldname not in SERVER_MANAGED_FIELDS
		):
			writable.add(field.fieldname)
	return writable


def _validate_payload(values: dict[str, Any], *, operation: str) -> None:
	unknown = sorted(set(values) - _meta_fieldnames() - SERVER_MANAGED_FIELDS)
	if unknown:
		frappe.throw(
			_("Unknown CRM Lead field(s): {0}.").format(", ".join(unknown)),
			frappe.ValidationError,
		)

	server_managed = sorted(set(values) & SERVER_MANAGED_FIELDS)
	if server_managed:
		frappe.throw(
			_("These CRM Lead fields are server-managed: {0}.").format(", ".join(server_managed)),
			frappe.ValidationError,
		)

	read_only = sorted(set(values) - _writable_fieldnames())
	if read_only:
		frappe.throw(
			_("These CRM Lead fields are read-only: {0}.").format(", ".join(read_only)),
			frappe.ValidationError,
		)



def _parse_filters(value: Any) -> dict[str, Any]:
	filters = _parse_json_object(value, "filters")
	filterable_fieldnames = {
		field.fieldname
		for field in frappe.get_meta(DOCTYPE).fields
		if field.fieldname and field.fieldtype not in NON_FILTERABLE_FIELD_TYPES
	}
	invalid = sorted(
		set(filters) - filterable_fieldnames - {"name", "creation", "modified", "owner", "modified_by"}
	)
	if invalid:
		frappe.throw(
			_("Unsupported CRM Lead filter field(s): {0}.").format(", ".join(invalid)),
			frappe.ValidationError,
		)
	return filters


def _validate_name(name: Any) -> str:
	if not isinstance(name, str) or not name.strip():
		frappe.throw(_("Lead name is required."), frappe.ValidationError)
	return name


def _api_payload(doc: Any) -> dict[str, Any]:
	as_dict = getattr(doc, "as_dict", None)
	return as_dict() if callable(as_dict) else dict(doc)


@frappe.whitelist(methods=["GET"])
def list_leads(
	filters: dict[str, Any] | str | None = None,
	search: str | None = None,
	start: int | str = 0,
	page_length: int | str = 20,
	order_by: str = "modified desc",
) -> dict[str, Any]:
	"""List permission-scoped Lead rows with optional search and pagination."""
	filters = _parse_filters(filters)
	start = _parse_int(start, "start", default=0, minimum=0)
	page_length = _parse_int(
		page_length,
		"page_length",
		default=20,
		minimum=1,
		maximum=MAX_PAGE_LENGTH,
	)
	order_by = _parse_order_by(order_by)

	search = str(search or "").strip()
	if len(search) > 140:
		frappe.throw(_("search must be 140 characters or fewer."), frappe.ValidationError)
	or_filters = None
	if search:
		like = f"%{search}%"
		or_filters = [[fieldname, "like", like] for fieldname in SEARCH_FIELDS]

	result = paged_list(
		DOCTYPE,
		LIST_FIELDS,
		filters=filters,
		or_filters=or_filters,
		start=start,
		page_length=page_length,
		order_by=order_by,
	)
	rows = result.pop("rows")
	return {**result, "leads": [_api_payload(row) for row in rows]}


@frappe.whitelist(methods=["GET"])
def get_lead(name: str) -> dict[str, Any]:
	"""Get one Lead after enforcing its read permission and row scope."""
	name = _validate_name(name)
	doc = frappe.get_doc(DOCTYPE, name)
	doc.check_permission("read")
	return _api_payload(doc)


@frappe.whitelist(methods=["POST"])
def create_lead(fields: dict[str, Any] | str | None = None, **direct_values: Any) -> dict[str, Any]:
	"""Create one Lead using only fields writable through the generic CRUD API."""
	values = _payload_from_arguments(fields, direct_values)
	if not values:
		frappe.throw(_("fields must be a non-empty object."), frappe.ValidationError)
	_validate_payload(values, operation="create")

	doc = frappe.new_doc(DOCTYPE)
	for fieldname, value in values.items():
		doc.set(fieldname, value)
	doc.insert()
	return _api_payload(doc)


@frappe.whitelist(methods=["POST", "PUT"])
def update_lead(
	name: str, fields: dict[str, Any] | str | None = None, **direct_values: Any
) -> dict[str, Any]:
	"""Partially update one Lead without bypassing command-owned workflows."""
	name = _validate_name(name)
	values = _payload_from_arguments(fields, direct_values)
	if not values:
		frappe.throw(_("fields must be a non-empty object."), frappe.ValidationError)
	_validate_payload(values, operation="update")

	doc = frappe.get_doc(DOCTYPE, name)
	doc.check_permission("write")
	for fieldname, value in values.items():
		doc.set(fieldname, value)
	doc.save()
	return _api_payload(doc)


@frappe.whitelist(methods=["DELETE", "POST"])
def delete_lead(name: str) -> dict[str, str]:
	"""Delete one Lead after enforcing its delete permission."""
	name = _validate_name(name)
	doc = frappe.get_doc(DOCTYPE, name)
	doc.check_permission("delete")
	doc.delete()
	return {"deleted": name}
